[package]
name = "ipkt-dcerpc"
description = "DCE/RPC transport (MS-RPCE) for the ipkt toolkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ipkt-core.workspace = true
thiserror.workspace = true
hex.workspace = true

[lints]
workspace = true
