[package]
name = "ipkt-ldap"
description = "LDAP client (RFC 4511 subset) for the ipkt toolkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ipkt-core.workspace = true
thiserror = { workspace = true }
tokio = { workspace = true, optional = true }

[features]
default = []
client = ["dep:tokio"]

[lints]
workspace = true
